### ISSUE TITLE
----

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [Michaelc2e/ComputerVision#1]
----

**Comment by misterpyrrhuloxia** [comment]
### Solution to Hammerpoint problem:
@Michaelc2e, as you know, the Hammerpoint being confused for a Turbocharger wasn't an issue till they changed it to a gold hop-up at the start of Season 16. I've been using your script `v1.27` ever since the start of the season because of this issue with the Hammerpoint not being recognized correctly and because of the optics not being recognized when they're ADS'd. And since `v1.27` is your last script build that isn't fully compiled, with the help of another user, I've been able to completely solve the issue with the Hammerpoint. This doesn't solve our problem with the optics, but it does at least eliminate one of the issues with all your scripts that have come after `v1.27.

Here's the solution that the other user helped me implement on `v1.27` that I believe will solve the Hammerpoint issue on your current script:

> 1. Add `P2020_H_HP` and `P2020_V_HP`
> 2. Add those to `ARTUNE` script
> 3. Copy and add anti-recoil script
> 4. Edit `Turbocharger` fire mode to `True` (so that you can use rapidfire)
> 
> ![Hammerpoint Fix](https://user-images.githubusercontent.com/9469151/220388673-fb379e23-7f57-40e4-b076-a7b1935c28a8.png)

I'm not sure what can be done to resolve the issue with the 2x, 3x, and 2-4x optics, but I'm sure that implementing the above fix in your latest script _should_ at least solve the issue with the Hammerpoint.

**Comment by Michaelc2e** [comment]
Hi, Pyrrhuloxia,

Wait several minutes. I’m gonna release the v1.33 to fix this. Please try.

Thank you for your feedback.

Michael
